server:
  port: 8086

discovery:
  port: 9999

spring:
  application:
    name: demo1-simulator

  datasource:
    url: jdbc:h2:file:./data/simulator1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always