server:
  port: 8087

spring:
  application:
    name: demo1-simulator2

  datasource:
    url: jdbc:h2:file:./data/simulator2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
